# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/send.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/send.proto',
  package='adddata',
  syntax='proto3',
  serialized_pb=_b('\n\x10proto/send.proto\x12\x07\x61\x64\x64\x64\x61ta\"\xd3\x01\n\x0b\x44\x61taRequest\x12\x30\n\x06Params\x18\x01 \x01(\x0b\x32 .adddata.DataRequest.ParamValues\x12\x0e\n\x06\x41\x63tion\x18\x02 \x01(\t\x12\x12\n\nChunkOrder\x18\x03 \x01(\r\x12\x11\n\tStartTime\x18\x04 \x01(\x04\x12\x0f\n\x07\x45ndTime\x18\x05 \x01(\x04\x12\x10\n\x08\x44uration\x18\x06 \x01(\x02\x12\x0f\n\x07Payload\x18\x07 \x01(\x0c\x12\x0c\n\x04Meta\x18\x08 \x01(\x0c\x1a\x19\n\x0bParamValues\x12\n\n\x02ID\x18\x01 \x01(\t\".\n\x0c\x44\x61taResponse\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x12\n\nChunkOrder\x18\x02 \x01(\rb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DATAREQUEST_PARAMVALUES = _descriptor.Descriptor(
  name='ParamValues',
  full_name='adddata.DataRequest.ParamValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='adddata.DataRequest.ParamValues.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=241,
)

_DATAREQUEST = _descriptor.Descriptor(
  name='DataRequest',
  full_name='adddata.DataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Params', full_name='adddata.DataRequest.Params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Action', full_name='adddata.DataRequest.Action', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ChunkOrder', full_name='adddata.DataRequest.ChunkOrder', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StartTime', full_name='adddata.DataRequest.StartTime', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='EndTime', full_name='adddata.DataRequest.EndTime', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Duration', full_name='adddata.DataRequest.Duration', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Payload', full_name='adddata.DataRequest.Payload', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Meta', full_name='adddata.DataRequest.Meta', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATAREQUEST_PARAMVALUES, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=241,
)


_DATARESPONSE = _descriptor.Descriptor(
  name='DataResponse',
  full_name='adddata.DataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='adddata.DataResponse.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ChunkOrder', full_name='adddata.DataResponse.ChunkOrder', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=289,
)

_DATAREQUEST_PARAMVALUES.containing_type = _DATAREQUEST
_DATAREQUEST.fields_by_name['Params'].message_type = _DATAREQUEST_PARAMVALUES
DESCRIPTOR.message_types_by_name['DataRequest'] = _DATAREQUEST
DESCRIPTOR.message_types_by_name['DataResponse'] = _DATARESPONSE

DataRequest = _reflection.GeneratedProtocolMessageType('DataRequest', (_message.Message,), dict(

  ParamValues = _reflection.GeneratedProtocolMessageType('ParamValues', (_message.Message,), dict(
    DESCRIPTOR = _DATAREQUEST_PARAMVALUES,
    __module__ = 'proto.send_pb2'
    # @@protoc_insertion_point(class_scope:adddata.DataRequest.ParamValues)
    ))
  ,
  DESCRIPTOR = _DATAREQUEST,
  __module__ = 'proto.send_pb2'
  # @@protoc_insertion_point(class_scope:adddata.DataRequest)
  ))
_sym_db.RegisterMessage(DataRequest)
_sym_db.RegisterMessage(DataRequest.ParamValues)

DataResponse = _reflection.GeneratedProtocolMessageType('DataResponse', (_message.Message,), dict(
  DESCRIPTOR = _DATARESPONSE,
  __module__ = 'proto.send_pb2'
  # @@protoc_insertion_point(class_scope:adddata.DataResponse)
  ))
_sym_db.RegisterMessage(DataResponse)


# @@protoc_insertion_point(module_scope)
